# Generated by Django 4.0.3 on 2022-03-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('names', models.CharField(max_length=70, verbose_name='Nombres')),
                ('lastnames', models.CharField(max_length=70, verbose_name='Apellidos')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('curp', models.CharField(max_length=70, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=70, verbose_name='RFc')),
                ('estadoCivil', models.CharField(max_length=70, verbose_name='Estado Civil')),
                ('estado', models.CharField(max_length=70, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=70, verbose_name='Municipio')),
                ('colonia', models.CharField(max_length=70, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=70, verbose_name='Calle')),
                ('numero', models.CharField(max_length=70, verbose_name='Numero')),
                ('password', models.CharField(max_length=70, verbose_name='Password')),
                ('img', models.CharField(max_length=150, verbose_name='Imagen')),
                ('rol', models.CharField(max_length=70, verbose_name='Rol')),
                ('google', models.BooleanField(default=False, verbose_name='Google')),
                ('facebook', models.BooleanField(default=False, verbose_name='Facebook')),
                ('codregistro', models.CharField(blank=True, max_length=6, verbose_name='Codigo de Verificación')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
