# Generated by Django 4.0.3 on 2022-03-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastnames',
            field=models.CharField(max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='names',
            field=models.CharField(max_length=200, verbose_name='Nombres'),
        ),
    ]
