# Generated by Django 4.0.3 on 2022-03-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(max_length=150, null=True, verbose_name='Imagen'),
        ),
    ]
