# Generated by Django 4.0.3 on 2022-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calle',
            field=models.CharField(max_length=70, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='colonia',
            field=models.CharField(max_length=70, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='curp',
            field=models.CharField(max_length=200, null=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(max_length=70, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estadoCivil',
            field=models.CharField(max_length=70, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='municipio',
            field=models.CharField(max_length=70, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero',
            field=models.CharField(max_length=70, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rfc',
            field=models.CharField(max_length=70, null=True, verbose_name='RFc'),
        ),
    ]
