# Generated by Django 4.0.3 on 2022-04-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AlterField(
            model_name='user',
            name='calle',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='codregistro',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Codigo de Verificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='colonia',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estadoCivil',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='municipio',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rfc',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='RFc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rol', verbose_name='Rol'),
        ),
    ]
