# Generated by Django 4.0.3 on 2022-03-27 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.CharField(max_length=200, verbose_name='Licencia')),
            ],
        ),
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialism', models.CharField(max_length=150, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_license', models.CharField(max_length=40, verbose_name='Licencia')),
                ('specialism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialism')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.JSONField(verbose_name='Lunes')),
                ('martes', models.JSONField(verbose_name='Martes')),
                ('miercoles', models.JSONField(verbose_name='Miercoles')),
                ('jueves', models.JSONField(verbose_name='Jueves')),
                ('viernes', models.JSONField(verbose_name='Viernes')),
                ('sabado', models.JSONField(verbose_name='Sabado')),
                ('domingo', models.JSONField(verbose_name='Domingo')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.clinic')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, verbose_name='Asuntos/Temas')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.clinic')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.meeting_topic')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.JSONField(verbose_name='Availability')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.clinic')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist')),
            ],
        ),
    ]
