# Generated by Django 4.0.3 on 2022-03-29 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='asunto',
        ),
        migrations.AddField(
            model_name='meeting',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.clinic'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='comments',
            field=models.TextField(max_length=400, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.meeting_topic'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='availability',
            field=models.JSONField(null=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.clinic'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting_topic',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.clinic'),
        ),
        migrations.AlterField(
            model_name='meeting_topic',
            name='topic',
            field=models.CharField(max_length=150, null=True, verbose_name='Asuntos/Temas'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.clinic'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='domingo',
            field=models.JSONField(null=True, verbose_name='Domingo'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='jueves',
            field=models.JSONField(null=True, verbose_name='Jueves'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lunes',
            field=models.JSONField(null=True, verbose_name='Lunes'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='martes',
            field=models.JSONField(null=True, verbose_name='Martes'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='miercoles',
            field=models.JSONField(null=True, verbose_name='Miercoles'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sabado',
            field=models.JSONField(null=True, verbose_name='Sabado'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='viernes',
            field=models.JSONField(null=True, verbose_name='Viernes'),
        ),
    ]
