# Generated by Django 4.0.3 on 2022-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_remove_meeting_asunto_meeting_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='domingo',
            field=models.JSONField(blank=True, verbose_name='Domingo'),
        ),
    ]
