# Generated by Django 4.0.3 on 2022-04-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_town'),
        ('specialist', '0006_alter_clinic_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country', verbose_name='Pais'),
        ),
    ]
