# Generated by Django 4.0.3 on 2022-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0008_clinic_postal_code_clinic_state_clinic_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='Street',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Google map'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='map_iframe',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Google map'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='number',
            field=models.IntegerField(default=None, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='suburb',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Google map'),
        ),
    ]
