# Generated by Django 4.0.3 on 2022-04-10 04:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0009_clinic_street_clinic_map_iframe_clinic_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='description_content',
            field=ckeditor.fields.RichTextField(default='sin texto'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='Street',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='suburb',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Colonia'),
        ),
    ]
