# Generated by Django 4.0.3 on 2022-04-10 15:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0010_specialist_description_content_alter_clinic_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='description_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='sin texto', null=True),
        ),
    ]
