# Generated by Django 4.0.3 on 2022-04-10 15:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0011_alter_specialist_description_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='description_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
