# Generated by Django 4.0.3 on 2022-04-10 16:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0015_alter_specialist_description_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='phrase',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Frase'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description_content',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
