# Generated by Django 4.0.3 on 2022-04-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0016_specialist_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='phrase',
            field=models.CharField(default='', max_length=200, verbose_name='Frase'),
        ),
    ]
