# Generated by Django 4.0.3 on 2022-04-10 23:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialist', '0017_alter_specialist_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='description_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='phrase',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Frase'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='professional_license',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Licencia'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.specialism'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.title'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
