# Generated by Django 4.0.3 on 2022-04-11 15:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0018_alter_specialist_description_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='other_Data',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
