# Generated by Django 4.0.3 on 2022-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0020_alter_clinic_map_iframe_alter_clinic_other_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image/clinic/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image/clinic/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image/clinic/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image/clinic/'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image/specialist/'),
        ),
    ]
