# Generated by Django 4.0.3 on 2022-04-15 21:25

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0021_clinic_fourth_image_clinic_principal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='title',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
