# Generated by Django 4.0.3 on 2022-04-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0023_availability_created_availability_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
