# Generated by Django 4.0.3 on 2022-04-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0024_specialist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Especiaista', 'verbose_name_plural': 'Especiaistas'},
        ),
    ]
